[package]
name = "stocks_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sqlite = "0.32.0"
chrono = "0.4"